### PR TITLE
Fix issue with wrong updated token balances

### LINKED ISSUE #473: Celo Balance not displaying on explorer

### PR DESCRIPTION
**Pull request by eruizgar91**
### Description

 Fix non updated coin balances.
 
 ### Other changes

No

### Tested

Done

### Issues

 - Fixes #473 

 ### Backwards compatibility

 _Brief explanation of why these changes are/are not backwards compatible._

### Checklist

  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I added code comments for anything non trivial.
  - [ ] I added documentation for my changes.
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/celo-org/monorepo to update the list and default values of env vars.
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools.

### CODE REVIEW

File: apps/indexer/lib/indexer/fetcher/internal_transaction.ex [hunk 1]
```diff
@@ -293,10 +298,10 @@ defmodule Indexer.Fetcher.InternalTransaction do
 
     case imports do
       {:ok, imported} ->
-        Accounts.drop(imported[:addreses])
+        Accounts.drop(imported[:addresses])
```
Comment (rkachowski) [inline apps/indexer/lib/indexer/fetcher/internal_transaction.ex:301]: oh wow good catch

**Review by rkachowski — APPROVED** [review]
